### PR TITLE
Resolves: #66

### LINKED ISSUE #66: purge_chain.sh doesn't delete local_testnet
`purge_chain.sh` currently has a hardcoded list of chains whose data-directories get deleted.

The `--chain=local` testnet gets stored under local_testnet which doesn't get deleted.

Also, have we thought about factoring out the list of possible chains + printing which chains haven't been deleted by purge_chain.sh after it runs?

### PR DESCRIPTION
**Pull request by DeepInThought**
Hi @raykyri,

Resolves #66 by adding dynamic lookup of executable file when `purge-chain.sh` is in the `scripts/` directory.  If none are found you can pass the `./puge-chain.sh --chain-name NAME` to manually set the name.  Then it will detect the operating system found and tag it.  Finally it will dive into the directory where chains are stored per the OS selection.  The end-user will be prompted to purge each entry found or ignore.

Let me know if you have any questions.

Sincerely, @DeepInThought

### CODE REVIEW

**Comment by drewstone** [comment]
I'll run through this soon but at first glance it would be great to remove the header at the top that looks like an advertisement and is project specific (while we welcome contributions, they shouldn't be shills for other projects).

Also there is no `scripts/build.sh` file anymore so that shouldn't be mentioned anymore.

**Comment by DeepInThought** [comment]
@drewstone Feel free to modify my project specific writing. Just copied over what I was using.

**Comment by DeepInThought** [comment]
Hi @drewstone,

I made edits as requested.  Let me know if you have any issues or questions.  I do not have a macOS handy, so if you could test it that would be great.

Here are a list of changes:

v0.1.2
- Fixed ShellCheck warnings and recommendations.
- Added the `--color` option for users that want to ignore color outputs.
- Provided more functions and proper switches.

v0.1.1
- Removed Substrate branding from heredoc.
- Made the script project agnostic as requested.
- Added a terminal and color checker to prevent unreadable messaging.
- Tweaked the OS detection message a bit.
- Script passes shfmt without any issues.

**Comment by drewstone** [comment]
Will test out soon, thanks!

**Pull request closed without merging**
