### PR TITLE
[WIP] Try out migration extraction

### PR DESCRIPTION
**Pull request by apopiak**
This PR tries to extract migration logic out of substrate into separate crates.

Very prototypical, *does not work, yet*.

see https://github.com/paritytech/polkadot-sdk/issues/353 for inspiration

### CODE REVIEW

**Comment by drewstone** [comment]
Maybe merge this into `time-travel` or is this intended to go directly to master?

**Comment by apopiak** [comment]
> Maybe merge this into `time-travel` or is this intended to go directly to master?

of course, thanks, will tweak tomorrow

**Comment by apopiak** [comment]
wrong base branch

**Comment by apopiak** [comment]
See https://github.com/hicommonwealth/edgeware-node/pull/179 for the actual PR

**Pull request closed without merging**
