### PR TITLE
updated vendor to point at commit 062bc84

### PR DESCRIPTION
**Pull request by YameenMalik**
The PR updates the frontier commit to latest one and fixes a minor bug with EthAPI invocation in node/rpc/src/lib.rs file.

### CODE REVIEW

**Comment by drewstone** [comment]
Can you fix the PR description to something shorter and answer the questions or remove them?

**Comment by drewstone** [comment]
You also need to update the CircleCI configuration to update the submodules so that the build runs sucessfully.

**Comment by drewstone** [comment]
Is this still being worked on?

**Comment by YameenMalik** [comment]
yeah was busy with other stuff, will update it tomorrow.

**Pull request merged**
